version: 2
registries:
  ghcr-registry:
    type: docker-registry
    url: ghcr.io
    username: akerl
    password: ${{ secrets.REPO_TOKEN }}
updates:
  - package-ecosystem: docker
    directory: /
    registries:
      - ghcr-registry
    schedule:
      interval: daily
    labels:
      - mergewhenready
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - mergewhenready
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    labels:
      - mergewhenready
