---
name: Publish
'on':
  push:
    tags:
    - "**"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Run Docker CI
      uses: akerl/.github/actions/base-docker@main
    - name: Publish images
      shell: bash
      run: ./meta/publish.sh
